# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amonnium
email: joaodiogooliveira@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  I am Amonnium, a hobbyist developer and technology enthusiast, dedicated to creating good and free software for everyone and sharing knowledge with the community.
  My projects are available on my GitHub profile, and they are:
  hello-world: my first project, when I was more young, presenting me and showing a Python "Hello, World!". Archived. Link: https://github.com/Amonnium/hello-world
  Apple Intelligence: a terminal-based Python simulation of the Apple Intelligence, the AI of Apple Inc. Archived. Link: https://github.com/Amonnium/Apple-Intelligence
  Hello World in Different Languages: a project that shows the "Hello, World!" program in different programming languages. Link: https://github.com/Amonnium/Hello-World-in-Different-Languages
  Calculate Pi Scripts: a project that contains scripts to calculate the value of Pi in different programming languages with different methods. My biggest project so far. Link: https://github.com/Amonnium/Calculate-Pi-Scripts
  amonnium.github.io: my personal website, which is this website. Link: https://amonnium.github.io/
github_username: Amonnium
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "João Oliveira"
  avatar : "/assets/images/Amonnium-GitHub.jpg"
  bio    : "A hobbyist developer and technology enthusiast, dedicated to creating good and free software for everyone and sharing knowledge with the community."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://amonnium.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Amonnium"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Amonnium"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/